// File:        EnergyReservation.cs
// Component:   Energy Slot Reservation
// Description: Model for documents in the EnergyReservation collection, including
//              reservation, QR and completion details.
// Author:      Gunathilaka K.K.N.M.

using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SolarMicrogrid.Api.Models;

public class EnergyReservation
{
    // Unique reservation id generated by MongoDB.
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string? Id { get; set; }

    // Reservation details

    // NIC of the prosumer who made the reservation.
    [BsonElement("nic")]
    public string NIC { get; set; } = string.Empty;

    // Id of the microgrid node, stored as a string.
    [BsonElement("nodeId")]
    public string NodeId { get; set; } = string.Empty;

    // Station name saved with the reservation for display.
    [BsonElement("stationName")]
    public string StationName { get; set; } = string.Empty;

    // Optional id of the booked slot.
    [BsonElement("slotId")]
    public string? SlotId { get; set; }

    // Start time of the booked slot (UTC).
    [BsonElement("slotStartTime")]
    public DateTime SlotStartTime { get; set; }

    // End time of the booked slot (UTC).
    [BsonElement("slotEndTime")]
    public DateTime SlotEndTime { get; set; }

    // Reserved energy amount in kWh.
    [BsonElement("energyKWh")]
    public double EnergyKWh { get; set; }

    // Pending, Approved, Completed, Cancelled or Rejected.
    [BsonElement("status")]
    public string Status { get; set; } = "Pending";

    [BsonElement("createdAt")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [BsonElement("updatedAt")]
    public DateTime? UpdatedAt { get; set; }

    [BsonElement("approvedAt")]
    public DateTime? ApprovedAt { get; set; }

    // Id of the user who approved the reservation.
    [BsonElement("approvedBy")]
    public string? ApprovedBy { get; set; }

    [BsonElement("cancelledAt")]
    public DateTime? CancelledAt { get; set; }

    // QR details

    // Single-use token encoded in the QR code. Null until a QR is generated.
    [BsonElement("qrToken")]
    public string? QrToken { get; set; }

    [BsonElement("qrGeneratedAt")]
    public DateTime? QrGeneratedAt { get; set; }

    // Time after which the QR token is no longer valid.
    [BsonElement("qrExpiresAt")]
    public DateTime? QrExpiresAt { get; set; }

    // Set when the QR is used, so it cannot be used again.
    [BsonElement("qrUsedAt")]
    public DateTime? QrUsedAt { get; set; }

    // Completion details

    [BsonElement("completedAt")]
    public DateTime? CompletedAt { get; set; }

    // Id of the Grid Operator who completed the transfer.
    [BsonElement("completedBy")]
    public string? CompletedBy { get; set; }

    [BsonElement("completedByNic")]
    public string? CompletedByNic { get; set; }

    // Energy actually delivered in kWh.
    [BsonElement("deliveredKWh")]
    public double? DeliveredKWh { get; set; }
}
